#! /bin/bash

cd /home/$(whoami)
mkdir exercise-upper
cd exercise-upper
mkdir exercise-lower
cd exercise-lower
touch test1.txt
touch test2.txt
mv test1.txt /home/$(whoami)/exercise-upper
mv test2.txt test2.sh
echo "#! /bin/bash" >> test2.sh
echo "pwd" >> test2.sh
echo "whoami" >> test2.sh
chmod +x test2.sh
./test2.sh
#! /bin/bash
echo "Enter website URL:"
read website
curl -s ${website} > temp.txt
if [ -s temp.txt ]
then
    echo "Yes this exists"
else
    echo "Nope this doesn't exist"
fi
rm temp.txt
#! /bin/bash
echo "What file do you want to find?"
read filename
where=$(pwd)
cd /home/$(whoami)
value=$(find "$(cd ..; pwd)" -name ${filename} | head -n 1)

if [ ${value} ]
then
    echo "Exists ${value}"
elif [ -d ${value} ]
then
    echo "Exists ${value}"
else
    echo "Does not exist"
fi
#! /bin/bash

echo "Name of file?"
read name
echo "Title?"
read title
cd ~
if [ -d "$(date "+%B-%Y")" ]; then
    cd $(date "+%B-%Y")
else
    mkdir $(date "+%B-%Y")
    cd $(date "+%B-%Y")
fi
touch ${name}$(date "+%d").md
echo "## ${title} Date: $(date "+%D")" >> ${name}$(date "+%d").md
vim ${name}$(date "+%d").md
echo "Enter your grade (A-F):"
read grade

case ${grade} in
    "A") echo "Brilliant";;
    "B") echo "Well done";;
    "C") echo "Not bad";;
    "D") echo "Could be better";;
    "E") echo "Not Great";;
    "F") echo "Bad";;
    *) echo "Don't recognise this grade";;
esac
#! /bin/bash

echo "Hello, what is your user name?"
read username
currentuser="$(whoami)"
if [ $username == $currentuser ]; then
        echo "You are the current logged in user"
else
        echo "You are not logged in"
fi
